import { afterEach, describe, expect, it, vi } from 'vitest'
import { EXECUTION_ENDPOINT, submitRemoteExecution } from '../src/execution/client.js'
import { canonicalExecutionRequest } from '../shared/execution-request.js'
import { sha256Hex } from '../shared/sha256.js'
import { signExecutionResult } from '../shared/execution-result-integrity.js'

const unsignedCapabilities=()=>({schema_version:'0.1',runners:['python'],network_policies:['deny'],limits:{max_source_bytes:65536,min_wall_ms:100,max_wall_ms:10000,min_output_bytes:1024,max_output_bytes:65536},execution_result_is_evidence:false,result_integrity:{required:false,algorithm:'ECDSA_P256_SHA256',key_id:null,public_jwk:null,verification_keys:[]}})
async function resultForRequest(request){return{schema_version:'0.1',job_id:'j1',request_id:request.request_id,received_at:'2026-08-17T06:00:00.000Z',completed_at:'2026-08-17T06:00:00.002Z',status:'completed',execution:{provider:'mock',runner:'python',exit_code:0,timed_out:false,wall_ms:2},result:{type:'text',stdout:'2\n',stderr:'',truncated:false},provenance:{source_sha256:await sha256Hex(request.source),request_sha256:await sha256Hex(canonicalExecutionRequest(request))}}}
async function signingFixture(keyId='test-signing-key'){const pair=await crypto.subtle.generateKey({name:'ECDSA',namedCurve:'P-256'},true,['sign','verify']);const privateJwk=await crypto.subtle.exportKey('jwk',pair.privateKey);const exported=await crypto.subtle.exportKey('jwk',pair.publicKey);const publicJwk={kty:exported.kty,crv:exported.crv,x:exported.x,y:exported.y};return{privateJwk,publicJwk,keyId}}
function requiredCapabilities(active,previous=[]){return{...unsignedCapabilities(),result_integrity:{required:true,algorithm:'ECDSA_P256_SHA256',key_id:active.keyId,public_jwk:active.publicJwk,verification_keys:[{key_id:active.keyId,public_jwk:active.publicJwk},...previous.map(key=>({key_id:key.keyId,public_jwk:key.publicJwk}))]}}}

afterEach(()=>vi.useRealTimers())

describe('remote execution client',()=>{
  it('uses a fresh nonce inside the canonical request and verifies provenance',async()=>{const source='print(1+1)';const requestId='req-client-0123456789';const fetchImpl=vi.fn(async(url,init)=>{expect(url).toBe('/v1/jobs');const body=JSON.parse(init.body);expect(body.request_id).toBe(requestId);expect(body.network_policy).toEqual({mode:'deny'});return new Response(JSON.stringify(await resultForRequest(body)),{status:200})});expect((await submitRemoteExecution({source,accessToken:'0123456789abcdef',capabilities:unsignedCapabilities(),requestIdFactory:()=>requestId,fetchImpl})).status).toBe('completed')})
  it('rejects a stale result from an earlier request nonce even for identical source',async()=>{const source='print(1)';const staleRequest={schema_version:'0.1',request_id:'req-stale-012345678',runner:'python',source,network_policy:{mode:'deny'},limits:{wall_ms:5000,output_bytes:65536}};const stale=await resultForRequest(staleRequest);await expect(submitRemoteExecution({source,accessToken:'0123456789abcdef',capabilities:unsignedCapabilities(),requestIdFactory:()=> 'req-fresh-012345678',fetchImpl:async()=>new Response(JSON.stringify(stale),{status:200})})).rejects.toThrow(/request provenance mismatch/i)})
  it('accepts a correctly signed remote result when signatures are required',async()=>{const fixture=await signingFixture();const source='print(2)';const requestId='req-signed-012345678';const capabilities=requiredCapabilities(fixture);const fetchImpl=async(url,init)=>{const body=JSON.parse(init.body);const envelope=await resultForRequest(body);envelope.integrity=await signExecutionResult(envelope,fixture.privateJwk,fixture.keyId);return new Response(JSON.stringify(envelope),{status:200})};const result=await submitRemoteExecution({source,accessToken:'0123456789abcdef',capabilities,requestIdFactory:()=>requestId,fetchImpl});expect(result.status).toBe('completed');expect(result.integrity.payload_version).toBe('2')})
  it('accepts an in-flight result signed by a previous rotation key',async()=>{const active=await signingFixture('active-key');const previous=await signingFixture('previous-key');const capabilities=requiredCapabilities(active,[previous]);const requestId='req-rotation-0123456';const fetchImpl=async(url,init)=>{const envelope=await resultForRequest(JSON.parse(init.body));envelope.integrity=await signExecutionResult(envelope,previous.privateJwk,previous.keyId);return new Response(JSON.stringify(envelope),{status:200})};const result=await submitRemoteExecution({source:'print(2)',accessToken:'0123456789abcdef',capabilities,requestIdFactory:()=>requestId,fetchImpl});expect(result.integrity.key_id).toBe('previous-key')})
  it('refreshes capabilities once when a valid response arrives under a newly rotated key',async()=>{const old=await signingFixture('old-key');const fresh=await signingFixture('fresh-key');const refreshCapabilities=vi.fn(async()=>requiredCapabilities(fresh,[old]));const fetchImpl=async(url,init)=>{const envelope=await resultForRequest(JSON.parse(init.body));envelope.integrity=await signExecutionResult(envelope,fresh.privateJwk,fresh.keyId);return new Response(JSON.stringify(envelope),{status:200})};const result=await submitRemoteExecution({source:'print(2)',accessToken:'0123456789abcdef',capabilities:requiredCapabilities(old),requestIdFactory:()=> 'req-refresh-01234567',fetchImpl,refreshCapabilities});expect(result.integrity.key_id).toBe('fresh-key');expect(refreshCapabilities).toHaveBeenCalledOnce()})
  it('rejects a signed result whose key is outside the trusted rotation set',async()=>{const active=await signingFixture('active-key');const outsider=await signingFixture('outsider-key');const capabilities=requiredCapabilities(active);const fetchImpl=async(url,init)=>{const envelope=await resultForRequest(JSON.parse(init.body));envelope.integrity=await signExecutionResult(envelope,outsider.privateJwk,outsider.keyId);return new Response(JSON.stringify(envelope),{status:200})};await expect(submitRemoteExecution({source:'print(2)',accessToken:'0123456789abcdef',capabilities,requestIdFactory:()=> 'req-outsider-0123456',fetchImpl})).rejects.toThrow(/not trusted/i)})
  it('rejects a tampered signed result',async()=>{const fixture=await signingFixture();const source='print(2)';const requestId='req-tamper-01234567';const capabilities=requiredCapabilities(fixture);const fetchImpl=async(url,init)=>{const body=JSON.parse(init.body);const envelope=await resultForRequest(body);envelope.integrity=await signExecutionResult(envelope,fixture.privateJwk,fixture.keyId);envelope.result.stdout='999\n';return new Response(JSON.stringify(envelope),{status:200})};await expect(submitRemoteExecution({source,accessToken:'0123456789abcdef',capabilities,requestIdFactory:()=>requestId,fetchImpl})).rejects.toThrow(/signature verification failed/i)})
  it('rejects unsigned remote results when signatures are required',async()=>{const fixture=await signingFixture();const capabilities=requiredCapabilities(fixture);await expect(submitRemoteExecution({source:'print(1)',accessToken:'0123456789abcdef',capabilities,requestIdFactory:()=> 'req-unsigned-0123456',fetchImpl:async(url,init)=>new Response(JSON.stringify(await resultForRequest(JSON.parse(init.body))),{status:200})})).rejects.toThrow(/signature is required/i)})
  it('aborts a remote request that exceeds the viewer-side wait budget',async()=>{vi.useFakeTimers();const fetchImpl=vi.fn((url,init)=>new Promise((resolve,reject)=>{init.signal.addEventListener('abort',()=>reject(new DOMException('Aborted','AbortError')),{once:true})}));const promise=submitRemoteExecution({source:'print(1)',accessToken:'0123456789abcdef',capabilities:unsignedCapabilities(),requestIdFactory:()=> 'req-timeout-01234567',fetchImpl});const rejection=expect(promise).rejects.toThrow(/timed out after 10000 ms/i);await vi.advanceTimersByTimeAsync(10_001);await rejection;expect(fetchImpl).toHaveBeenCalledOnce()})
  it('fails before fetch when capabilities are missing',async()=>{const fetchImpl=vi.fn();await expect(submitRemoteExecution({source:'print(1)',accessToken:'0123456789abcdef',fetchImpl})).rejects.toThrow(/capabilities/i);expect(fetchImpl).not.toHaveBeenCalled()})
  it('never accepts a caller-supplied execution endpoint',()=>expect(EXECUTION_ENDPOINT).toBe('/v1/jobs'))
})
