import { describe, expect, it } from 'vitest'
import { createApplication } from '../src/app.js'
import { createMockProvider } from '../src/providers/mock.js'
const env={CONTROL_API_TOKEN:'0123456789abcdef0123456789abcdef',VIEWER_ORIGIN:'https://viewer.example',ALLOW_UNLIMITED_DEV:'true',ALLOW_UNSIGNED_RESULTS_DEV:'true'}
const requestBody={schema_version:'0.1',request_id:'req-0123456789abcdef',runner:'python',source:'print(1 + 1)',network_policy:{mode:'deny'},limits:{wall_ms:5000,output_bytes:65536}}
function jobRequest(extra={}){return new Request('https://control.example/v1/jobs',{method:'POST',headers:{authorization:`Bearer ${env.CONTROL_API_TOKEN}`,'content-type':'application/json',origin:env.VIEWER_ORIGIN},body:JSON.stringify(requestBody),...extra})}
describe('control plane app',()=>{
  it('requires bearer auth',async()=>{const app=createApplication(()=>createMockProvider());const request=jobRequest({headers:{'content-type':'application/json'}});expect((await app(request,env)).status).toBe(401)})
  it('rejects unexpected browser origins',async()=>{const app=createApplication(()=>createMockProvider());const request=jobRequest();request.headers.set('origin','https://evil.example');expect((await app(request,env)).status).toBe(403)})
  it('rejects an oversized declared body before provider execution',async()=>{let called=false;const app=createApplication(()=>({async executePython(){called=true;return{provider:'mock',stdout:'',stderr:'',exitCode:0,timedOut:false}}}));const request=jobRequest();request.headers.set('content-length',String(200000));const response=await app(request,env);expect(response.status).toBe(413);expect((await response.json()).error).toBe('body_too_large');expect(called).toBe(false)})
  it('rejects invalid UTF-8 request bytes before provider execution',async()=>{let called=false;const app=createApplication(()=>({async executePython(){called=true;return{provider:'mock',stdout:'',stderr:'',exitCode:0,timedOut:false}}}));const request=new Request('https://control.example/v1/jobs',{method:'POST',headers:{authorization:`Bearer ${env.CONTROL_API_TOKEN}`,'content-type':'application/json',origin:env.VIEWER_ORIGIN},body:new Uint8Array([0xc3,0x28])});const response=await app(request,env);expect(response.status).toBe(400);expect((await response.json()).error).toBe('invalid_utf8_body');expect(called).toBe(false)})
  it('returns a canonical execution envelope in explicit unsigned dev mode',async()=>{const app=createApplication(()=>createMockProvider({stdout:'2\n'}));const response=await app(jobRequest(),env);expect(response.status).toBe(200);const value=await response.json();expect(value.status).toBe('completed');expect(value.execution.provider).toBe('mock');expect(value.result.stdout).toBe('2\n');expect(value.provenance.source_sha256).toMatch(/^[0-9a-f]{64}$/);expect(value).not.toHaveProperty('integrity')})
  it('fails closed before provider execution when production signing is missing',async()=>{let called=false;const app=createApplication(()=>({async executePython(){called=true;return{provider:'mock',stdout:'',stderr:'',exitCode:0,timedOut:false}}}));const response=await app(jobRequest(),{...env,ALLOW_UNSIGNED_RESULTS_DEV:'false'});expect(response.status).toBe(503);expect(called).toBe(false)})
  it('rejects malformed provider output',async()=>{const app=createApplication(()=>({async executePython(){return{provider:'mock',stdout:'ok',stderr:'',exitCode:0,timedOut:false,secret:'nope'}}}));const response=await app(jobRequest(),env);expect(response.status).toBe(502)})
  it('does not turn provider failure into a judgment state',async()=>{const app=createApplication(()=>({async executePython(){throw new Error('provider unavailable')}}));const response=await app(jobRequest(),env);const value=await response.json();expect(response.status).toBe(502);expect(value.error).toBe('provider_failure');expect(value).not.toHaveProperty('judgment')})
})
