import { describe, expect, it } from 'vitest'
import { canonicalizeExecutionResult } from '../src/canonicalize.js'
const request={schema_version:'0.1',request_id:'req-0123456789abcdef',runner:'python',source:'print("ok")',network_policy:{mode:'deny'},limits:{wall_ms:1000,output_bytes:1024}}
describe('canonical execution result',()=>{
  it('caps combined stdout/stderr output',async()=>{const value=await canonicalizeExecutionResult({jobId:'j1',request,raw:{provider:'mock',stdout:'a'.repeat(900),stderr:'b'.repeat(900),exitCode:0,timedOut:false},wallMs:4});const total=new TextEncoder().encode(value.result.stdout+value.result.stderr).byteLength;expect(total).toBeLessThanOrEqual(1024);expect(value.result.truncated).toBe(true)})
  it('records request id and control-plane audit times',async()=>{const value=await canonicalizeExecutionResult({jobId:'j-audit',request,raw:{provider:'mock',stdout:'ok\n',stderr:'',exitCode:0,timedOut:false},wallMs:2,receivedAt:'2026-08-17T06:00:00.000Z',completedAt:'2026-08-17T06:00:00.002Z'});expect(value.request_id).toBe(request.request_id);expect(value.received_at).toBe('2026-08-17T06:00:00.000Z');expect(value.completed_at).toBe('2026-08-17T06:00:00.002Z')})
  it('rejects reversed audit time',async()=>{await expect(canonicalizeExecutionResult({jobId:'j-time',request,raw:{provider:'mock',stdout:'',stderr:'',exitCode:0,timedOut:false},wallMs:2,receivedAt:'2026-08-17T06:00:01.000Z',completedAt:'2026-08-17T06:00:00.000Z'})).rejects.toThrow(/must not precede/i)})
  it('reports timeout as execution failure rather than epistemic false',async()=>{const value=await canonicalizeExecutionResult({jobId:'j2',request,raw:{provider:'mock',stdout:'',stderr:'',exitCode:null,timedOut:true},wallMs:1000});expect(value.status).toBe('failed');expect(value.execution.timed_out).toBe(true);expect(value).not.toHaveProperty('judgment')})
  it('marks provider-side output overflow failed and truncated even if exit code is zero',async()=>{const value=await canonicalizeExecutionResult({jobId:'j3',request,raw:{provider:'mock',stdout:'a'.repeat(1024),stderr:'',exitCode:0,timedOut:false,outputLimited:true},wallMs:20});expect(value.status).toBe('failed');expect(value.result.truncated).toBe(true);expect(value).not.toHaveProperty('judgment')})
})
