import './styles.css'
import { MAX_PACKAGE_BYTES } from './protocol/limits.js'
import { parseAndValidatePackage } from './protocol/validate.js'
import { createEventStore } from './store/event-store.js'
import { projectAt } from './projection/projector.js'
import { createPlaybackController } from './playback/controller.js'
import { renderView } from './renderer/dom.js'
import { MAX_EXECUTION_RESULT_BYTES, parseAndValidateExecutionResult } from './execution/validate-result.js'
import { clearExecutionResult, renderExecutionResult } from './execution/render-result.js'
import { submitRemoteExecution } from './execution/client.js'
import { fetchExecutionCapabilities, safeExecutionLimits } from './execution/capabilities.js'

const viewer=document.getElementById('viewer'),status=document.getElementById('status'),fileInput=document.getElementById('package-file'),resultFileInput=document.getElementById('execution-result-file'),resultRoot=document.getElementById('execution-result'),resultDemoButton=document.getElementById('load-demo-execution'),cursorLabel=document.getElementById('cursor-label'),remoteForm=document.getElementById('remote-execution-form'),remoteSource=document.getElementById('remote-source'),remoteToken=document.getElementById('remote-token'),remoteRun=document.getElementById('remote-run'),remoteNote=document.getElementById('remote-execution-note')
const buttons={prev:document.getElementById('prev'),play:document.getElementById('play'),next:document.getElementById('next'),live:document.getElementById('live')}
let store=null,controller=null,previous=null,executionCapabilities=null
function setStatus(message,error=false){status.textContent=message;status.classList.toggle('error',error)}
function draw(cursor){if(!store)return;const current=projectAt(store,cursor);renderView(viewer,current,previous);previous=current;cursorLabel.textContent=`Event ${current.cursor} / ${store.length}${current.cursor===store.length?' · Live':' · Replay'}`;buttons.play.textContent=controller?.playing?'⏸ Pause':'▶ Play'}
function loadPackage(pkg,label){controller?.destroy();store=createEventStore(pkg);previous=null;controller=createPlaybackController({maxCursor:store.length,onCursor:draw,intervalMs:850});draw(store.length);setStatus(`${label} loaded · ${store.length} validated events`)}
async function loadBuiltInDemo(){try{const response=await fetch('/examples/demo-events.json',{credentials:'same-origin'});if(!response.ok)throw new Error(`HTTP ${response.status}`);loadPackage(parseAndValidatePackage(await response.text()),'Built-in demo')}catch(error){setStatus(`Demo load failed: ${error.message}`,true)}}
async function loadExecutionDemo(){try{const response=await fetch('/examples/demo-execution-result.json',{credentials:'same-origin'});if(!response.ok)throw new Error(`HTTP ${response.status}`);renderExecutionResult(resultRoot,parseAndValidateExecutionResult(await response.text()));setStatus('Safe execution-result demo loaded. Judgment state was not modified.')}catch(error){setStatus(`Execution demo load failed: ${error.message}`,true)}}
async function loadCapabilities(){executionCapabilities=null;remoteRun.disabled=true;remoteNote.textContent='Checking the control plane safety contract…';try{const caps=await fetchExecutionCapabilities();const safe=safeExecutionLimits(caps);executionCapabilities=caps;remoteRun.disabled=false;remoteNote.textContent=`Control plane verified: Python only · outbound network denied · ${Math.floor(safe.max_source_bytes/1024)} KiB source · ${safe.wall_ms} ms · ${Math.floor(safe.output_bytes/1024)} KiB output.`}catch(error){remoteNote.textContent=`Remote execution disabled: ${error.message}`;setStatus('Remote execution safety handshake failed. Static Viewer and replay remain available.',true)}}
fileInput.addEventListener('change',async()=>{const file=fileInput.files?.[0];if(!file)return;try{if(file.size>MAX_PACKAGE_BYTES)throw new Error(`File exceeds ${MAX_PACKAGE_BYTES} bytes`);loadPackage(parseAndValidatePackage(await file.text()),file.name)}catch(error){setStatus(`Import rejected: ${error.message}`,true)}finally{fileInput.value=''}})
resultFileInput.addEventListener('change',async()=>{const file=resultFileInput.files?.[0];if(!file)return;try{if(file.size>MAX_EXECUTION_RESULT_BYTES)throw new Error(`File exceeds ${MAX_EXECUTION_RESULT_BYTES} bytes`);renderExecutionResult(resultRoot,parseAndValidateExecutionResult(await file.text()));setStatus(`${file.name} inspected as execution data only. No evidence or judgment was changed.`)}catch(error){setStatus(`Execution result rejected: ${error.message}`,true)}finally{resultFileInput.value=''}})
buttons.prev.addEventListener('click',()=>controller?.step(-1));buttons.next.addEventListener('click',()=>controller?.step(1));buttons.live.addEventListener('click',()=>controller?.live());buttons.play.addEventListener('click',()=>{if(!controller)return;controller.playing?controller.pause():controller.play();buttons.play.textContent=controller.playing?'⏸ Pause':'▶ Play'});resultDemoButton.addEventListener('click',loadExecutionDemo)
remoteForm.addEventListener('submit',async event=>{event.preventDefault();if(remoteRun.disabled||!executionCapabilities)return;remoteRun.disabled=true;setStatus('Submitting isolated execution job…');const token=remoteToken.value;remoteToken.value='';try{const envelope=await submitRemoteExecution({source:remoteSource.value,accessToken:token,capabilities:executionCapabilities});renderExecutionResult(resultRoot,envelope);setStatus(`Managed execution ${envelope.status}. Result was not promoted to evidence.`)}catch(error){setStatus(error.message,true)}finally{remoteRun.disabled=!executionCapabilities}})
clearExecutionResult(resultRoot);loadBuiltInDemo();loadCapabilities()
